/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package as.level.notes;

/**
 *
 * @author Arielle Rudolph
 */
public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPpr1 = new javax.swing.JPanel();
        lblPpr1 = new javax.swing.JLabel();
        btn1Ppr1 = new javax.swing.JButton();
        btn2Ppr1 = new javax.swing.JButton();
        btn3Ppr1 = new javax.swing.JButton();
        btn4ppr1 = new javax.swing.JButton();
        btn5Ppr1 = new javax.swing.JButton();
        btn6Ppr1 = new javax.swing.JButton();
        btn7Ppr1 = new javax.swing.JButton();
        btn8Ppr1 = new javax.swing.JButton();
        btn9Ppr1 = new javax.swing.JButton();
        btn10Ppr1 = new javax.swing.JButton();
        btn11Ppr1 = new javax.swing.JButton();
        pnlPpr2 = new javax.swing.JPanel();
        lblPpr2Up = new javax.swing.JLabel();
        lblPpr2DOWN = new javax.swing.JLabel();
        btn1Ppr2 = new javax.swing.JButton();
        btn2Ppr2 = new javax.swing.JButton();
        btn3Ppr2 = new javax.swing.JButton();
        btn4Ppr2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPpr1.setBackground(new java.awt.Color(116, 79, 198));
        pnlPpr1.setForeground(new java.awt.Color(116, 79, 198));

        lblPpr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblPpr1.setForeground(new java.awt.Color(255, 255, 255));
        lblPpr1.setText("Paper 1 Theory Fundamentals");

        btn1Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn1Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn1Ppr1.setText("1 - Information Representation");
        btn1Ppr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1Ppr1ActionPerformed(evt);
            }
        });

        btn2Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn2Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn2Ppr1.setText("2 - Communication");

        btn3Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn3Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn3Ppr1.setText("3 - Hardware");

        btn4ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn4ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn4ppr1.setText("4 -Logic Gates & Circuits");

        btn5Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn5Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn5Ppr1.setText("5 - Processor fundamentals");

        btn6Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn6Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn6Ppr1.setText("6 - Assembly language programming");

        btn7Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn7Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn7Ppr1.setText("7 - Monitoring & control systems");

        btn8Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn8Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn8Ppr1.setText("8 - System Software");

        btn9Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn9Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn9Ppr1.setText("9 - Security, Privacy and Data");
        btn9Ppr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9Ppr1ActionPerformed(evt);
            }
        });

        btn10Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn10Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn10Ppr1.setText("10 - Ethics & ownership");

        btn11Ppr1.setBackground(new java.awt.Color(254, 198, 1));
        btn11Ppr1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn11Ppr1.setText("11 - Databases");

        javax.swing.GroupLayout pnlPpr1Layout = new javax.swing.GroupLayout(pnlPpr1);
        pnlPpr1.setLayout(pnlPpr1Layout);
        pnlPpr1Layout.setHorizontalGroup(
            pnlPpr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPpr1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPpr1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(pnlPpr1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlPpr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn11Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlPpr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn10Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn9Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn8Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn7Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn6Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn5Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn4ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn3Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn2Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn1Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPpr1Layout.setVerticalGroup(
            pnlPpr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPpr1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblPpr1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn3Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn4ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn5Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn6Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn7Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn8Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn9Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn10Ppr1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn11Ppr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPpr2.setBackground(new java.awt.Color(116, 79, 198));

        lblPpr2Up.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblPpr2Up.setForeground(new java.awt.Color(255, 255, 255));
        lblPpr2Up.setText("Paper 2 Fundamental Problem-Solving");

        lblPpr2DOWN.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        lblPpr2DOWN.setForeground(new java.awt.Color(255, 255, 255));
        lblPpr2DOWN.setText("and Programming Skills");

        btn1Ppr2.setBackground(new java.awt.Color(254, 198, 1));
        btn1Ppr2.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        btn1Ppr2.setText("9 - Algorithm Design and Problem-Solving");

        btn2Ppr2.setBackground(new java.awt.Color(254, 198, 1));
        btn2Ppr2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn2Ppr2.setText("10 - Data Types and Structures");

        btn3Ppr2.setBackground(new java.awt.Color(254, 198, 1));
        btn3Ppr2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn3Ppr2.setText("11 - Programming");

        btn4Ppr2.setBackground(new java.awt.Color(254, 198, 1));
        btn4Ppr2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btn4Ppr2.setText("12 - Data Representation");

        javax.swing.GroupLayout pnlPpr2Layout = new javax.swing.GroupLayout(pnlPpr2);
        pnlPpr2.setLayout(pnlPpr2Layout);
        pnlPpr2Layout.setHorizontalGroup(
            pnlPpr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPpr2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lblPpr2DOWN, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPpr2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(pnlPpr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPpr2Layout.createSequentialGroup()
                        .addComponent(lblPpr2Up, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPpr2Layout.createSequentialGroup()
                        .addGroup(pnlPpr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn2Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn1Ppr2)
                            .addComponent(btn3Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))))
        );
        pnlPpr2Layout.setVerticalGroup(
            pnlPpr2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPpr2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPpr2Up, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPpr2DOWN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn2Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn3Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn4Ppr2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnlPpr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPpr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPpr1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPpr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1Ppr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1Ppr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1Ppr1ActionPerformed

    private void btn9Ppr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9Ppr1ActionPerformed
            // TODO add your handling code here:
            SecPriDat9 main = new SecPriDat9();
            main.setVisible(true);
            this.setVisible(false);
            
    }//GEN-LAST:event_btn9Ppr1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10Ppr1;
    private javax.swing.JButton btn11Ppr1;
    private javax.swing.JButton btn1Ppr1;
    private javax.swing.JButton btn1Ppr2;
    private javax.swing.JButton btn2Ppr1;
    private javax.swing.JButton btn2Ppr2;
    private javax.swing.JButton btn3Ppr1;
    private javax.swing.JButton btn3Ppr2;
    private javax.swing.JButton btn4Ppr2;
    private javax.swing.JButton btn4ppr1;
    private javax.swing.JButton btn5Ppr1;
    private javax.swing.JButton btn6Ppr1;
    private javax.swing.JButton btn7Ppr1;
    private javax.swing.JButton btn8Ppr1;
    private javax.swing.JButton btn9Ppr1;
    private javax.swing.JLabel lblPpr1;
    private javax.swing.JLabel lblPpr2DOWN;
    private javax.swing.JLabel lblPpr2Up;
    private javax.swing.JPanel pnlPpr1;
    private javax.swing.JPanel pnlPpr2;
    // End of variables declaration//GEN-END:variables
}
