/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package as.level.notes;

/**
 *
 * @author Arielle Rudolph
 */
public class InfoRep1 extends javax.swing.JFrame {

    /**
     * Creates new form InfoRep1
     */
    public InfoRep1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblCh1ttl = new javax.swing.JLabel();
        tbpnsect = new javax.swing.JTabbedPane();
        pnlMulMed = new javax.swing.JPanel();
        tbpnMulMed = new javax.swing.JTabbedPane();
        pnlImgs = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlSound = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtSound = new javax.swing.JTextArea();
        pnlComp = new javax.swing.JPanel();
        tbpnComp = new javax.swing.JTabbedPane();
        pnlCompTech = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtCompTech = new javax.swing.JTextArea();
        pnlQandRev = new javax.swing.JPanel();
        pnlQandRevDate = new javax.swing.JTabbedPane();
        pnl9Feb = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt9Feb = new javax.swing.JTextArea();
        tbpndatrep = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtnumsys = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnoq = new javax.swing.JTextArea();
        pnlIntCoNo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInCoNo = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtIntCoText = new javax.swing.JTextArea();
        pnlOvrQuest = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblch1chapno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 204));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblCh1ttl.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        lblCh1ttl.setText("Information Representation");

        pnlMulMed.setBackground(new java.awt.Color(102, 102, 255));

        pnlImgs.setBackground(new java.awt.Color(51, 255, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("vector graphic - a graphic consisting of drawing objects defined in a drawing list\n\tdrawing object - a component defined by geometric formula and associated properties\n\tdrawing list - contains one set of values for each drawing object\nbit maps - not geometrically defined shapes\n\tthe concept that lies in the creation of a bit map file is a pixel\n\tpixel - short for picture element; the smallest identifiable component of a bit- map image defined by two properties: position and colour\n\tcolour depth - the number of bits used to represent one pixel\n\tBit depth - the number of bits used to represent each of the red, green and blue colours\n\timage resolution - the number of pixels in the bitmap defined as the product of the width and height values\n\tScreen resolution - the product of width and height values for the number of pixels the screen can display");
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlImgsLayout = new javax.swing.GroupLayout(pnlImgs);
        pnlImgs.setLayout(pnlImgsLayout);
        pnlImgsLayout.setHorizontalGroup(
            pnlImgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlImgsLayout.setVerticalGroup(
            pnlImgsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImgsLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnMulMed.addTab("Images", pnlImgs);

        jScrollPane8.setBackground(new java.awt.Color(102, 255, 102));

        txtSound.setColumns(20);
        txtSound.setRows(5);
        txtSound.setText("* Sound - variations of pressure detected by the human ear\n* to store sound electronically the original analog sound signal has to be converted\n\t* Steps to converting sound\n\t1 apply band-limiting filter\n\t2 put into analog-to-digital converter\n* band limiter - removes the frequencies that a human ear cannot detect and could cause problems in the coding if not removed\nSampling - taking measurements at regular intervals and storing the value\nSampling resolution - the number of bits used to store each sample \nSampling rate -the number of samples taken per second.\nanalogue data -data obtained by measurement of physical property \ndigital data - data that has been stored as a binary value which can be one of a discrete range of values");
        jScrollPane8.setViewportView(txtSound);

        javax.swing.GroupLayout pnlSoundLayout = new javax.swing.GroupLayout(pnlSound);
        pnlSound.setLayout(pnlSoundLayout);
        pnlSoundLayout.setHorizontalGroup(
            pnlSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSoundLayout.setVerticalGroup(
            pnlSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSoundLayout.createSequentialGroup()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnMulMed.addTab("Sound", pnlSound);

        javax.swing.GroupLayout pnlMulMedLayout = new javax.swing.GroupLayout(pnlMulMed);
        pnlMulMed.setLayout(pnlMulMedLayout);
        pnlMulMedLayout.setHorizontalGroup(
            pnlMulMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMulMedLayout.createSequentialGroup()
                .addComponent(tbpnMulMed)
                .addContainerGap())
        );
        pnlMulMedLayout.setVerticalGroup(
            pnlMulMedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMulMedLayout.createSequentialGroup()
                .addComponent(tbpnMulMed)
                .addContainerGap())
        );

        tbpnsect.addTab("Multimedia", pnlMulMed);

        pnlComp.setBackground(new java.awt.Color(51, 51, 255));

        pnlCompTech.setBackground(new java.awt.Color(51, 255, 255));

        txtCompTech.setColumns(20);
        txtCompTech.setRows(5);
        txtCompTech.setText("lossless compression - coding techniques that allow subsequent decoding to recreate exactly the original file\nlossy compression - coding techniques that cause some information to be lost so that the exact original file cannot be recovered in subsequent decoding\n* compression application will recognise patterns in files that it can compress\n* lossless compression technique is run length encoding\n\tused for bit maps\n");
        jScrollPane6.setViewportView(txtCompTech);

        javax.swing.GroupLayout pnlCompTechLayout = new javax.swing.GroupLayout(pnlCompTech);
        pnlCompTech.setLayout(pnlCompTechLayout);
        pnlCompTechLayout.setHorizontalGroup(
            pnlCompTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompTechLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCompTechLayout.setVerticalGroup(
            pnlCompTechLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompTechLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnComp.addTab("compression Techniques", pnlCompTech);

        javax.swing.GroupLayout pnlCompLayout = new javax.swing.GroupLayout(pnlComp);
        pnlComp.setLayout(pnlCompLayout);
        pnlCompLayout.setHorizontalGroup(
            pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpnComp)
                .addContainerGap())
        );
        pnlCompLayout.setVerticalGroup(
            pnlCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompLayout.createSequentialGroup()
                .addComponent(tbpnComp)
                .addContainerGap())
        );

        tbpnsect.addTab("Compression", pnlComp);

        pnl9Feb.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txt9Feb.setColumns(20);
        txt9Feb.setRows(5);
        jScrollPane7.setViewportView(txt9Feb);

        javax.swing.GroupLayout pnl9FebLayout = new javax.swing.GroupLayout(pnl9Feb);
        pnl9Feb.setLayout(pnl9FebLayout);
        pnl9FebLayout.setHorizontalGroup(
            pnl9FebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl9FebLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl9FebLayout.setVerticalGroup(
            pnl9FebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
        );

        pnlQandRevDate.addTab("09 - 02", pnl9Feb);

        javax.swing.GroupLayout pnlQandRevLayout = new javax.swing.GroupLayout(pnlQandRev);
        pnlQandRev.setLayout(pnlQandRevLayout);
        pnlQandRevLayout.setHorizontalGroup(
            pnlQandRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQandRevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlQandRevDate)
                .addContainerGap())
        );
        pnlQandRevLayout.setVerticalGroup(
            pnlQandRevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQandRevLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlQandRevDate)
                .addContainerGap())
        );

        tbpnsect.addTab("Questions & revision", pnlQandRev);

        jPanel1.setBackground(new java.awt.Color(204, 0, 153));

        txtnumsys.setColumns(20);
        txtnumsys.setRows(5);
        txtnumsys.setText("denary numbers - also known as decimal numbers, are written using one of the symbols 0 - 9 for each denary digit.\nbit - a digit in the binary number system written using either of the symbols: 0 or 1\nbyte - a group of 8 bits treated as a single unit\nnibble - group of 4 bits treated as a single unit\n");
        jScrollPane1.setViewportView(txtnumsys);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpndatrep.addTab("number systems", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 0, 153));

        txtnoq.setColumns(20);
        txtnoq.setRows(5);
        txtnoq.setText("decimal prefix- a prefix to define the magnitude of a value. Examples are kilo, mega and tera representing 10 to the power of 3, 6, 9, and 12 respectively\nBinary prefix - A prefix to define the magnitude of a value. Examples are kibi, mebi, gibi and tebi representing factors of 2 to the power of 10, 20, 30 and 40\n\trespectively.");
        jScrollPane2.setViewportView(txtnoq);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpndatrep.addTab("numbers & quantities", jPanel2);

        pnlIntCoNo.setBackground(new java.awt.Color(204, 0, 204));

        txtInCoNo.setColumns(20);
        txtInCoNo.setRows(5);
        jScrollPane3.setViewportView(txtInCoNo);

        javax.swing.GroupLayout pnlIntCoNoLayout = new javax.swing.GroupLayout(pnlIntCoNo);
        pnlIntCoNo.setLayout(pnlIntCoNoLayout);
        pnlIntCoNoLayout.setHorizontalGroup(
            pnlIntCoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntCoNoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlIntCoNoLayout.setVerticalGroup(
            pnlIntCoNoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntCoNoLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpndatrep.addTab("internal coding of numbers", pnlIntCoNo);

        jPanel3.setBackground(new java.awt.Color(204, 0, 204));

        txtIntCoText.setColumns(20);
        txtIntCoText.setRows(5);
        txtIntCoText.setText("ASCII - Stands for American Standard Code for Information Interchange;\n\t- it is made up of 7 bits\n\t- each character is made of 7 bits meaning that there are 128\nUnicode - Created as ASCII did not cover all the characters needed\n\t- each character is made of 11 bits meaning that the maximum value is 2048 meaning it consists of 2048 characters");
        jScrollPane4.setViewportView(txtIntCoText);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpndatrep.addTab("internal coding of text", jPanel3);

        tbpnsect.addTab("Data Representation", tbpndatrep);

        pnlOvrQuest.setBackground(new java.awt.Color(0, 255, 0));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane9.setViewportView(jTextArea2);

        javax.swing.GroupLayout pnlOvrQuestLayout = new javax.swing.GroupLayout(pnlOvrQuest);
        pnlOvrQuest.setLayout(pnlOvrQuestLayout);
        pnlOvrQuestLayout.setHorizontalGroup(
            pnlOvrQuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOvrQuestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlOvrQuestLayout.setVerticalGroup(
            pnlOvrQuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOvrQuestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbpnsect.addTab("Questions", pnlOvrQuest);

        lblch1chapno.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblch1chapno.setText("Chapter 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(264, 264, 264)
                .addComponent(lblch1chapno, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCh1ttl)
                .addGap(287, 287, 287))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbpnsect)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(lblch1chapno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCh1ttl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(tbpnsect)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    HomeScreen main = new HomeScreen();
        main.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoRep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoRep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoRep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoRep1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoRep1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblCh1ttl;
    private javax.swing.JLabel lblch1chapno;
    private javax.swing.JPanel pnl9Feb;
    private javax.swing.JPanel pnlComp;
    private javax.swing.JPanel pnlCompTech;
    private javax.swing.JPanel pnlImgs;
    private javax.swing.JPanel pnlIntCoNo;
    private javax.swing.JPanel pnlMulMed;
    private javax.swing.JPanel pnlOvrQuest;
    private javax.swing.JPanel pnlQandRev;
    private javax.swing.JTabbedPane pnlQandRevDate;
    private javax.swing.JPanel pnlSound;
    private javax.swing.JTabbedPane tbpnComp;
    private javax.swing.JTabbedPane tbpnMulMed;
    private javax.swing.JTabbedPane tbpndatrep;
    private javax.swing.JTabbedPane tbpnsect;
    private javax.swing.JTextArea txt9Feb;
    private javax.swing.JTextArea txtCompTech;
    private javax.swing.JTextArea txtInCoNo;
    private javax.swing.JTextArea txtIntCoText;
    private javax.swing.JTextArea txtSound;
    private javax.swing.JTextArea txtnoq;
    private javax.swing.JTextArea txtnumsys;
    // End of variables declaration//GEN-END:variables
}
