/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package as.level.notes;

/**
 *
 * @author Arielle Rudolph
 */
public class SecPriDat9 extends javax.swing.JFrame {

    /**
     * Creates new form SecPriDat9
     */
    public SecPriDat9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblchap9 = new javax.swing.JLabel();
        lblchaphed9 = new javax.swing.JLabel();
        tbChap9 = new javax.swing.JTabbedPane();
        pnlDef = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlThreats = new javax.swing.JPanel();
        tbThreats = new javax.swing.JTabbedPane();
        pnlThrIntro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtarThrIntro = new javax.swing.JTextArea();
        pnlMalware = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtarThrMalwr = new javax.swing.JTextArea();
        pnlVulner = new javax.swing.JPanel();
        txtChap9Vun = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pnlProData = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        pnlProSys = new javax.swing.JPanel();
        pnlIntProSys = new javax.swing.JTabbedPane();
        pnlProsys = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtSafBak = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtAuthPrac = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtFireAnt = new javax.swing.JTextArea();
        pnlValVer = new javax.swing.JPanel();
        tbValVar = new javax.swing.JTabbedPane();
        pnlVal = new javax.swing.JPanel();
        txtarVal = new javax.swing.JScrollPane();
        txtVal = new javax.swing.JTextArea();
        pnlVar = new javax.swing.JPanel();
        txtarVar = new javax.swing.JScrollPane();
        txtVar = new javax.swing.JTextArea();
        btnBac9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblchap9.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        lblchap9.setText("Chapter 9");
        lblchap9.setToolTipText("");
        getContentPane().add(lblchap9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        lblchaphed9.setFont(new java.awt.Font("Jokerman", 0, 18)); // NOI18N
        lblchaphed9.setText("Security, Privacy and Data Integrity");
        getContentPane().add(lblchaphed9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 380, 30));

        tbChap9.setBackground(new java.awt.Color(0, 204, 255));

        pnlDef.setBackground(new java.awt.Color(102, 153, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("-> Data integrity - a requirement for data to be accurate and up to date.\n-> Data privacy - a requirement for data to be avaliable only to authorised users.\n-> Data protection law - \n\t-> the major focus of the law is a person's personal data.\n\t-> data is supplied to an organisation by an agreeing individual - it may only be used for agreed purpose\n\t-> the law obliges organisations to ensure the privacy and integrity of the data.\n-> Data security - a requirement for data to be avaliable for use when needed, ensures that only authorised users have\n\t access to the system and data can be recovered if lost or corrupted\n\t-> data security must be reached before either data integrity or data privacy can be achieved\n\t-> data security alone does not guarentee data integrity or privacy\n-> Primary aims of system security measures\n\t-> ensures that the system carries out the tasks\n\t-> to ensure that only authorised users have access to the system");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout pnlDefLayout = new javax.swing.GroupLayout(pnlDef);
        pnlDef.setLayout(pnlDefLayout);
        pnlDefLayout.setHorizontalGroup(
            pnlDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDefLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDefLayout.setVerticalGroup(
            pnlDefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDefLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbChap9.addTab("Definitions", pnlDef);

        pnlThreats.setBackground(new java.awt.Color(204, 153, 255));

        tbThreats.setBackground(new java.awt.Color(255, 153, 255));

        pnlThrIntro.setBackground(new java.awt.Color(153, 153, 255));

        TxtarThrIntro.setColumns(20);
        TxtarThrIntro.setRows(5);
        TxtarThrIntro.setText("-> threats to the security of the system \n\t-> an individual user not taking appropriate care\n\t-> internal mismanagement\n\t-> natural disasters\n\t-> unauthorised intrusion\n\t-> malware");
        jScrollPane2.setViewportView(TxtarThrIntro);

        javax.swing.GroupLayout pnlThrIntroLayout = new javax.swing.GroupLayout(pnlThrIntro);
        pnlThrIntro.setLayout(pnlThrIntroLayout);
        pnlThrIntroLayout.setHorizontalGroup(
            pnlThrIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThrIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlThrIntroLayout.setVerticalGroup(
            pnlThrIntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThrIntroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbThreats.addTab("introduction", pnlThrIntro);

        txtarThrMalwr.setColumns(20);
        txtarThrMalwr.setRows(5);
        txtarThrMalwr.setText("-> Malware - malicious software that has intention of causing harm to a system or its contents.\n-> Types of Malware -\n\t-> Virus - Tries to replicate itself inside other executable code\n\t-> Worm - runs independently and transfers itself to other network hosts.\n\t-> logic bomb - stays inactive until some condition is met\n\t-> Trojan horse - Malware disguised as something positive that replaces all or part of a previously usable program\n\t-> Spyware - collects information and transfers it to another system\n\t-> Bot - takes control of another computer and uses it to launch attacks\n\t-> Phishing - Sending an email or message from an apparently legitimate source requesting confidential information\n\t-> Pharming - Setting up a fake website that seems legitimate to extract personal data\n\t-> Key logger - Recording keyboard usage by the legitimate user of the system");
        jScrollPane3.setViewportView(txtarThrMalwr);

        javax.swing.GroupLayout pnlMalwareLayout = new javax.swing.GroupLayout(pnlMalware);
        pnlMalware.setLayout(pnlMalwareLayout);
        pnlMalwareLayout.setHorizontalGroup(
            pnlMalwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMalwareLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlMalwareLayout.setVerticalGroup(
            pnlMalwareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMalwareLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbThreats.addTab("malware", pnlMalware);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("* System vunerability arising from user activity.\n\t* Examples not involving malware\n\t\t* Weak password\n\t\t* User not recogising phishing/pharming attack\n\t* Examples including malware\n\t\t* Download of file from internet\n\t\t* attatchment of malware-inducing storage device\n\t\t* opening an email attatchment\n\n* Vunerability arising from within the system itself\n\t* operating systems lack good security\n\t* lack of protection from malicious hardware\n\t* system overwrites itself buffer overflow - creates holes for hackers to exploit\n");
        txtChap9Vun.setViewportView(jTextArea2);

        javax.swing.GroupLayout pnlVulnerLayout = new javax.swing.GroupLayout(pnlVulner);
        pnlVulner.setLayout(pnlVulnerLayout);
        pnlVulnerLayout.setHorizontalGroup(
            pnlVulnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVulnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtChap9Vun, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVulnerLayout.setVerticalGroup(
            pnlVulnerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVulnerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtChap9Vun, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbThreats.addTab("vulnerability", pnlVulner);

        javax.swing.GroupLayout pnlThreatsLayout = new javax.swing.GroupLayout(pnlThreats);
        pnlThreats.setLayout(pnlThreatsLayout);
        pnlThreatsLayout.setHorizontalGroup(
            pnlThreatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbThreats)
        );
        pnlThreatsLayout.setVerticalGroup(
            pnlThreatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThreatsLayout.createSequentialGroup()
                .addComponent(tbThreats)
                .addContainerGap())
        );

        tbChap9.addTab("Threats", pnlThreats);

        jTabbedPane1.setBackground(new java.awt.Color(51, 255, 51));

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("* Accidental loss of data\n\t* System crash can result in loss of unsaved data as well as data corruption\n\t* Disc or tape is corrupted and destroyed\n\t* File is erased or overwritten by mistake\n\t* location of file is lost\n* There should always be a backup proceedure\n\t* Full backup made at regular intervals\n\t* Multiple generations of full backup are kept in storage\n\t* incremental backups are made on a daily basis\n* Backups are stored in a seperate, fireproof and floodproof location\n");
        jScrollPane7.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Recovering from data loss", jPanel4);

        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jTextArea7.setText("* Different categories of user with different needs, with respect to the data they are allowed to see and use.\n* The solution is to have an authorisation policy which gives different access rights to different files for different individuals\n ");
        jScrollPane8.setViewportView(jTextArea7);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Restricting access to data", jPanel5);

        javax.swing.GroupLayout pnlProDataLayout = new javax.swing.GroupLayout(pnlProData);
        pnlProData.setLayout(pnlProDataLayout);
        pnlProDataLayout.setHorizontalGroup(
            pnlProDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProDataLayout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        pnlProDataLayout.setVerticalGroup(
            pnlProDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        tbChap9.addTab("Protecting data", pnlProData);

        pnlProSys.setBackground(new java.awt.Color(102, 0, 153));
        pnlProSys.setForeground(new java.awt.Color(102, 0, 153));

        pnlIntProSys.setBackground(new java.awt.Color(0, 0, 102));
        pnlIntProSys.setForeground(new java.awt.Color(204, 255, 255));

        pnlProsys.setBackground(new java.awt.Color(102, 0, 255));

        txtSafBak.setBackground(new java.awt.Color(153, 153, 255));
        txtSafBak.setColumns(20);
        txtSafBak.setRows(5);
        txtSafBak.setText("* Disaster Recovery \n\t* Continuity of operation is important because they are integral to the operations of a basic organisation\n\t* If a system were to shut down it must be guarenteed to start-up again\n\t* There should always be a disaster-recovery contingency\n\tHotsite - a full system ready to replace a normally-operational one and is seperate from the main system.\n* Safe system update\n\t* Organisations need to have a replacement site to fill in for its original counterpart if under maintainence");
        jScrollPane4.setViewportView(txtSafBak);

        javax.swing.GroupLayout pnlProsysLayout = new javax.swing.GroupLayout(pnlProsys);
        pnlProsys.setLayout(pnlProsysLayout);
        pnlProsysLayout.setHorizontalGroup(
            pnlProsysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProsysLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProsysLayout.setVerticalGroup(
            pnlProsysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProsysLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlIntProSys.addTab("Safety and Backups", pnlProsys);

        txtAuthPrac.setBackground(new java.awt.Color(204, 204, 255));
        txtAuthPrac.setColumns(20);
        txtAuthPrac.setRows(5);
        txtAuthPrac.setText("* User authentication - the varification of a user's identity\n\t* The main security of an user account is/are password(s)\n* Good Practice\n\t* Not leaving your computer unattended\n\t* Not attaching portable storage devices onto a computer\n* Digital signiture - if you recieve an email you can check the identity of the sender; you can insist on a digital signiture from the sender\n \n\t");
        jScrollPane5.setViewportView(txtAuthPrac);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlIntProSys.addTab("Authorisation Practice", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 0, 204));

        jScrollPane6.setBackground(new java.awt.Color(102, 51, 255));
        jScrollPane6.setForeground(new java.awt.Color(102, 51, 255));

        txtFireAnt.setBackground(new java.awt.Color(153, 153, 255));
        txtFireAnt.setColumns(20);
        txtFireAnt.setRows(5);
        txtFireAnt.setText("* Firewall - hardware or software that monitors and controls network traffic\n\t* A firewall can inspect system addresses identified in the transmission of data & can sometimes inspect the data itself.\n* AntiVirus Software -\n\t* Aimed at combating any type of malware\n\t* Regular scans detect any malware and remove it\n\t* Intrusion detection system can be installed, and will input an audit of system use & look for instances of unusual activity");
        jScrollPane6.setViewportView(txtFireAnt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pnlIntProSys.addTab("Firewall and antivirus", jPanel3);

        javax.swing.GroupLayout pnlProSysLayout = new javax.swing.GroupLayout(pnlProSys);
        pnlProSys.setLayout(pnlProSysLayout);
        pnlProSysLayout.setHorizontalGroup(
            pnlProSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlIntProSys)
        );
        pnlProSysLayout.setVerticalGroup(
            pnlProSysLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProSysLayout.createSequentialGroup()
                .addComponent(pnlIntProSys)
                .addContainerGap())
        );

        tbChap9.addTab("Protecting Systems", pnlProSys);

        pnlValVer.setBackground(new java.awt.Color(102, 102, 255));
        pnlValVer.setForeground(new java.awt.Color(255, 255, 255));

        tbValVar.setBackground(new java.awt.Color(204, 153, 255));

        pnlVal.setBackground(new java.awt.Color(153, 204, 255));

        txtVal.setColumns(20);
        txtVal.setRows(5);
        txtVal.setText("-> Validation - a check that data entered is the correct type and format. it does not guarentee that the data is accurate.\n-> Types of checks -\n\t-> presense check - Checks if input is blank\n\t-> format check - example would be dd/mm/yr\n\t-> length check - checks for correct amount of characters\n\t-> range check - prevents invalid numbers from being input\n\t-> limit check - checks that input values are within the required range\n\t-> type check - checks that only valid characters are used\n\t-> existance check - checks that files that are being uploaded exist\n \n");
        txtarVal.setViewportView(txtVal);

        javax.swing.GroupLayout pnlValLayout = new javax.swing.GroupLayout(pnlVal);
        pnlVal.setLayout(pnlValLayout);
        pnlValLayout.setHorizontalGroup(
            pnlValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtarVal, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlValLayout.setVerticalGroup(
            pnlValLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtarVal, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbValVar.addTab("Validation", pnlVal);

        pnlVar.setBackground(new java.awt.Color(204, 255, 204));

        txtVar.setColumns(20);
        txtVar.setRows(5);
        txtVar.setText("-> Verification - a confirmation of data recieved by a system.\n\n* ONE-BIT PARITY CHECK\n\t1. At the transmitting end, the number of 1's in the 7-bit code is counted\n\t2. If the count gives an even number, the parity bit is set to 0.\n\t3. If the count gives an odd number, the parity bit is set to 1.\n\t4. This is repeated for every byte in the transmission.\n\t5. At the recieving end, the number of 1's in the 8-bit code is counted\n\t6. If the count gives an even number the byte is accepted\n\t7. This is repeated for every byte in the transmission\n\tnote: the parity check cannot identify errors and simply informs the user that something went wrong");
        txtarVar.setViewportView(txtVar);

        javax.swing.GroupLayout pnlVarLayout = new javax.swing.GroupLayout(pnlVar);
        pnlVar.setLayout(pnlVarLayout);
        pnlVarLayout.setHorizontalGroup(
            pnlVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtarVar, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlVarLayout.setVerticalGroup(
            pnlVarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtarVar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbValVar.addTab("Verification", pnlVar);

        javax.swing.GroupLayout pnlValVerLayout = new javax.swing.GroupLayout(pnlValVer);
        pnlValVer.setLayout(pnlValVerLayout);
        pnlValVerLayout.setHorizontalGroup(
            pnlValVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValVerLayout.createSequentialGroup()
                .addComponent(tbValVar)
                .addContainerGap())
        );
        pnlValVerLayout.setVerticalGroup(
            pnlValVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValVerLayout.createSequentialGroup()
                .addComponent(tbValVar)
                .addContainerGap())
        );

        tbChap9.addTab("Validation & verification", pnlValVer);

        getContentPane().add(tbChap9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 750, 330));

        btnBac9.setBackground(new java.awt.Color(153, 0, 0));
        btnBac9.setFont(new java.awt.Font("Sylfaen", 3, 14)); // NOI18N
        btnBac9.setForeground(new java.awt.Color(255, 255, 255));
        btnBac9.setText("Back ");
        btnBac9.setToolTipText("Back to home screen");
        btnBac9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBac9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBac9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        setSize(new java.awt.Dimension(866, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBac9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBac9ActionPerformed
        // TODO add your handling code here:
        HomeScreen main = new HomeScreen();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBac9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecPriDat9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecPriDat9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecPriDat9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecPriDat9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecPriDat9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TxtarThrIntro;
    private javax.swing.JButton btnBac9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JLabel lblchap9;
    private javax.swing.JLabel lblchaphed9;
    private javax.swing.JPanel pnlDef;
    private javax.swing.JTabbedPane pnlIntProSys;
    private javax.swing.JPanel pnlMalware;
    private javax.swing.JPanel pnlProData;
    private javax.swing.JPanel pnlProSys;
    private javax.swing.JPanel pnlProsys;
    private javax.swing.JPanel pnlThrIntro;
    private javax.swing.JPanel pnlThreats;
    private javax.swing.JPanel pnlVal;
    private javax.swing.JPanel pnlValVer;
    private javax.swing.JPanel pnlVar;
    private javax.swing.JPanel pnlVulner;
    private javax.swing.JTabbedPane tbChap9;
    private javax.swing.JTabbedPane tbThreats;
    private javax.swing.JTabbedPane tbValVar;
    private javax.swing.JTextArea txtAuthPrac;
    private javax.swing.JScrollPane txtChap9Vun;
    private javax.swing.JTextArea txtFireAnt;
    private javax.swing.JTextArea txtSafBak;
    private javax.swing.JTextArea txtVal;
    private javax.swing.JTextArea txtVar;
    private javax.swing.JTextArea txtarThrMalwr;
    private javax.swing.JScrollPane txtarVal;
    private javax.swing.JScrollPane txtarVar;
    // End of variables declaration//GEN-END:variables
}
